cask "font-roboto-mono-jp" do
  version "7.1.0"
  sha256 "3d63d48669b27aa7aabc564ffb36799924fc852bb12898e77b3d2e89ae51e508"

  url "https://github.com/mjun0812/RobotoMonoJP/releases/download/v#{version}/RobotoMonoJP-Fonts-v#{version}.zip"
  name "Roboto Mono JP"
  desc "Monospace fonts combining Roboto Mono, Japanese fonts, and Nerd Fonts"
  homepage "https://github.com/mjun0812/RobotoMonoJP"

  font "RobotoMonoBizUd-Regular.ttf"
  font "RobotoMonoBizUd-Bold.ttf"
  font "RobotoMonoBizUd-Italic.ttf"
  font "RobotoMonoBizUd-BoldItalic.ttf"
  font "RobotoMonoGenJyuu-Regular.ttf"
  font "RobotoMonoGenJyuu-Bold.ttf"
  font "RobotoMonoGenJyuu-Italic.ttf"
  font "RobotoMonoGenJyuu-BoldItalic.ttf"
  font "RobotoMonoLineSeed-Regular.ttf"
  font "RobotoMonoLineSeed-Bold.ttf"
  font "RobotoMonoLineSeed-Italic.ttf"
  font "RobotoMonoLineSeed-BoldItalic.ttf"
  font "RobotoMonoNoto-Regular.ttf"
  font "RobotoMonoNoto-Bold.ttf"
  font "RobotoMonoNoto-Italic.ttf"
  font "RobotoMonoNoto-BoldItalic.ttf"
  font "RobotoMonoPlex-Regular.ttf"
  font "RobotoMonoPlex-Bold.ttf"
  font "RobotoMonoPlex-Italic.ttf"
  font "RobotoMonoPlex-BoldItalic.ttf"
  font "RobotoMonoZenKaku-Regular.ttf"
  font "RobotoMonoZenKaku-Bold.ttf"
  font "RobotoMonoZenKaku-Italic.ttf"
  font "RobotoMonoZenKaku-BoldItalic.ttf"
end
