cask "font-roboto-mono-jp" do
  version "6.1.1"
  sha256 "c21358127516304207b477cb814424dad172ab3c0aff72ed7161fd0bb8902cbf"

  url "https://github.com/mjun0812/RobotoMonoJP/releases/download/v#{version}/RobotoMonoJP-Fonts-v#{version}.zip"
  name "Roboto Mono JP"
  desc "Monospace fonts combining Roboto Mono, Japanese fonts, and Nerd Fonts"
  homepage "https://github.com/mjun0812/RobotoMonoJP"

  font "RobotoMonoBizUd-Regular.ttf"
  font "RobotoMonoBizUd-Bold.ttf"
  font "RobotoMonoBizUd-Italic.ttf"
  font "RobotoMonoBizUd-BoldItalic.ttf"
  font "RobotoMonoGenJyuu-Regular.ttf"
  font "RobotoMonoGenJyuu-Bold.ttf"
  font "RobotoMonoGenJyuu-Italic.ttf"
  font "RobotoMonoGenJyuu-BoldItalic.ttf"
  font "RobotoMonoLineSeed-Regular.ttf"
  font "RobotoMonoLineSeed-Bold.ttf"
  font "RobotoMonoLineSeed-Italic.ttf"
  font "RobotoMonoLineSeed-BoldItalic.ttf"
  font "RobotoMonoNoto-Regular.ttf"
  font "RobotoMonoNoto-Bold.ttf"
  font "RobotoMonoNoto-Italic.ttf"
  font "RobotoMonoNoto-BoldItalic.ttf"
  font "RobotoMonoPlex-Regular.ttf"
  font "RobotoMonoPlex-Bold.ttf"
  font "RobotoMonoPlex-Italic.ttf"
  font "RobotoMonoPlex-BoldItalic.ttf"
  font "RobotoMonoZenKaku-Regular.ttf"
  font "RobotoMonoZenKaku-Bold.ttf"
  font "RobotoMonoZenKaku-Italic.ttf"
  font "RobotoMonoZenKaku-BoldItalic.ttf"
end
